vim.g.mapleader = ' '
vim.g.maplocalleader = '\\'
vim.o.clipboard = 'unnamedplus'
vim.o.undofile = true
vim.o.undolevels = 10000
vim.o.backup = false
vim.o.swapfile = false
vim.o.confirm = true
vim.o.updatetime = 250
vim.o.virtualedit = 'block'
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true
vim.o.signcolumn = 'yes'
vim.o.termguicolors = true
vim.o.laststatus = 3
vim.o.cmdheight = 0
vim.o.showmode = false
vim.o.showcmd = false
vim.o.ruler = false
vim.o.showtabline = 0
vim.o.pumheight = 10
vim.o.pumblend = 10
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true -- I don't wanna hop in immediately
vim.o.expandtab = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.smartindent = true
vim.o.breakindent = true
vim.o.wrap = false
vim.o.scrolloff = 5
vim.o.sidescrolloff = 5
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.foldlevelstart = 99
vim.o.foldmethod = 'expr'
vim.o.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.o.timeoutlen = 500 -- Time to wait for key sequence (ms)
vim.o.completeopt = 'menu,menuone,noselect' -- Always show menu, even for single match, don't auto-select
vim.o.wildmode = 'longest:full,full'
vim.o.winborder = 'rounded'
vim.o.shortmess = 'aAOSTIWc'
